export const IMAGE_POOL = [
  "https://images.pexels.com/photos/29440437/pexels-photo-29440437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210634/pexels-photo-31210634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/36745051/pexels-photo-36745051.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/5302663/pexels-photo-5302663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/38128369/pexels-photo-38128369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745603/pexels-photo-12745603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31196818/pexels-photo-31196818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/37125137/pexels-photo-37125137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745602/pexels-photo-12745602.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210664/pexels-photo-31210664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
];

export type SeedCategory = {
  name: string;
  nameTa: string;
  slug: string;
  tagline: string;
  description: string;
  accent: string;
  icon: string;
  imageUrl: string;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: "Kids Special",
    nameTa: "கிட்ஸ் ஸ்பெஷல்",
    slug: "kids-special",
    tagline: "Drone, Guns, Simba, Unicorn & Low-Sound Novelty Fireworks for Kids",
    description: "Vibrant low-sound fountains, guns, drones and colorful novelty fireworks specially curated for children and safe family fun.",
    accent: "#FFD700",
    icon: "sparkles",
    imageUrl: "/categories/kids-special.jpg",
  },
  {
    name: "Fountains",
    nameTa: "ஃபவுண்டன் வகைகள்",
    slug: "fountains",
    tagline: "Tom & Jerry, Peacock, Water Queen & Novelty Fountains",
    description: "Vibrant shower cones, multi-step fountains and tri-color pyro fountain displays.",
    accent: "#FF8C00",
    icon: "flame",
    imageUrl: "/categories/fountains.jpg",
  },
  {
    name: "Short Items",
    nameTa: "சிறிய ரக வெடிகள்",
    slug: "single-sound",
    tagline: "Classic Sivakasi Lakshmi, Kuruvi & 2 Sound crackers",
    description: "Traditional single and double report crackers with sharp decibel report.",
    accent: "#FF3131",
    icon: "volume",
    imageUrl: "/categories/single-sound.jpg",
  },
  {
    name: "Bijili Crackers",
    nameTa: "பிஜிலி வெடி",
    slug: "bijili-crackers",
    tagline: "Red and Stripped bijili 100 bags",
    description: "Crisp crackling bijilis packed in 100 piece bags.",
    accent: "#FF3131",
    icon: "zap",
    imageUrl: "/categories/bijili-crackers.jpg",
  },
  {
    name: "Ground Chakkars",
    nameTa: "நிலச்சக்கரம்",
    slug: "ground-chakkar",
    tagline: "Ground Chakkar Big, Special, Deluxe and Spinners",
    description: "High-rpm ground wheels and spinners for kids and families.",
    accent: "#00D26A",
    icon: "disc",
    imageUrl: "/categories/ground-chakkar.jpg",
  },
  {
    name: "Twinkling Stars",
    nameTa: "ட்விங்க்ளிங் ஸ்டார்",
    slug: "twinkling-star",
    tagline: "1½' & 4' Twinkling Star ropes",
    description: "Continuous twinkling stars and star ropes.",
    accent: "#F5D982",
    icon: "star",
    imageUrl: "/categories/twinkling-star.jpg",
  },
  {
    name: "Flower Pots",
    nameTa: "பூச்சட்டி",
    slug: "flower-pots",
    tagline: "Flower Pots Big, Special, Asoka & Colour Kotti",
    description: "Classic high-rise golden and silver fountains with low smoke composition.",
    accent: "#D4AF37",
    icon: "sparkles",
    imageUrl: "/categories/flower-pots.jpg",
  },
  {
    name: "Pencils",
    nameTa: "பென்சில்ஸ்",
    slug: "candles",
    tagline: "Nayagara Falls Handle pencils",
    description: "Multi-color fountain handle pencils.",
    accent: "#00D26A",
    icon: "flame",
    imageUrl: "/categories/candles.jpg",
  },
  {
    name: "Rockets",
    nameTa: "ராக்கெட்",
    slug: "rockets",
    tagline: "Musical Rocket and Rocket Bomb",
    description: "High-flying rockets with whistling sound and bright canopy bursts.",
    accent: "#FF8C00",
    icon: "rocket",
    imageUrl: "/categories/rockets.jpg",
  },
  {
    name: "Bombs",
    nameTa: "பாம்புகள்",
    slug: "bombs",
    tagline: "King Bomb, Classic Bomb, Jurassic & Paper Bombs",
    description: "High-decibel sound bombs with heavy casing and water-resistant fuse.",
    accent: "#FF3131",
    icon: "bomb",
    imageUrl: "/categories/bombs.jpg",
  },
  {
    name: "Aerial Shots",
    nameTa: "வான வெடி",
    slug: "sky-shots",
    tagline: "Chotta Fancy, 2″ Fancy, 3.5″ Smash & Nayagara Falls",
    description: "Single sky displays and aerial shells.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Multi Shots",
    nameTa: "மல்டி ஷாட்ஸ்",
    slug: "multi-shots",
    tagline: "15 to 240 Shots Colour sky repeaters",
    description: "Aerial multi-color sky repeaters and celebration set outs.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Sparklers",
    nameTa: "மத்தாப்பு",
    slug: "sparklers",
    tagline: "7cm to 50cm Electric, Colour, Green & Red sparklers",
    description: "Child-safe sparklers with bright light and low smoke emission.",
    accent: "#F5D982",
    icon: "wand",
    imageUrl: "/categories/sparklers.jpg",
  },
  {
    name: "Colour Matches & Novelties",
    nameTa: "தீப்பெட்டி & ஃபேன்சி",
    slug: "novelties",
    tagline: "Roll Caps, Ring Caps, Black Serpents & Mega Matches",
    description: "Match boxes, caps, serpents and novelties.",
    accent: "#FF8C00",
    icon: "gift",
    imageUrl: "/categories/novelties.jpg",
  },
  {
    name: "Gift Boxes",
    nameTa: "கிஃப்ட் பாக்ஸ்",
    slug: "gift-boxes",
    tagline: "21 to 51 Items & Family Combo / VIP Packs",
    description: "Curated festival packages containing a balanced mix across all categories.",
    accent: "#D4AF37",
    icon: "package",
    imageUrl: "/categories/gift-boxes.jpg",
  },
];

export const SEED_PRODUCTS: Record<string, [string, number, string, number, string?, string?, number?][]> = {
  "kids-special": [
    ["Free Fire Gun", 750, "1 Box (1 Pc)", 1, "N", undefined, 150],
    ["Little Simba", 1300, "1 Box (3 Pcs)", 3, "B", undefined, 260],
    ["Magical Unicorn", 1350, "1 Box (2 Pcs)", 2, "F", undefined, 270],
    ["Drone", 775, "1 Box (5 Pcs)", 5, "F", undefined, 155],
    ["Insta Selfie", 675, "1 Box (5 Pcs)", 5, "F", undefined, 135],
    ["Pink Nova", 1300, "1 Box (2 Pcs)", 2, "N", undefined, 260],
    ["Violet Nebula", 1350, "1 Box (2 Pcs)", 2, "N", undefined, 270],
    ["Pocket / Lima / Jazz Stars", 500, "1 Box (5 Pcs)", 5, "B", undefined, 100],
  ],

  "single-sound": [
    ["2 3/4\" Kuruvi", 35, "1 Box", 5, "B", undefined, 7],
    ["3 1/2\" Laxmi", 60, "1 Box", 5, "B", undefined, 12],
    ["4\" Laxmi", 80, "1 Box", 5, "F", undefined, 16],
    ["4\" Deluxe Laxmi", 125, "1 Box", 5, "N", undefined, 25],
    ["4\" Gold Laxmi", 160, "1 Box", 5, "P", undefined, 32],
    ["5\" Laxmi", 240, "1 Box", 5, "PN", undefined, 48],
    ["2 Sound", 150, "1 Box", 5, "B", undefined, 30],
  ],

  "bijili-crackers": [
    ["Red Bijili 100", 150, "1 Bag (100 Pcs)", 100, "B", undefined, 30],
    ["Stripped Bijili 100", 170, "1 Bag (100 Pcs)", 100, "F", undefined, 34],
  ],

  "ground-chakkar": [
    ["Ground Chakkar Big 10Pcs", 210, "1 Box (10 Pcs)", 10, "B", undefined, 42],
    ["Ground Chakkar Special", 380, "1 Box (10 Pcs)", 10, "F", undefined, 76],
    ["Ground Chakkar Deluxe", 625, "1 Box (10 Pcs)", 10, "P", undefined, 125],
    ["Spinner Deluxe", 850, "1 Box (5 Pcs)", 5, "N", undefined, 170],
    ["wire chakkar", 1000, "1 Box", 10, "N", undefined, 200],
  ],

  "twinkling-star": [
    ["1 1/2' Twinkling Stars", 120, "1 Box (10 Pcs)", 10, "B", undefined, 24],
    ["4' Twinkling Stars", 325, "1 Box (10 Pcs)", 10, "F", undefined, 65],
  ],

  "flower-pots": [
    ["Flower Pots Big", 380, "1 Box (10 Pcs)", 10, "B", undefined, 76],
    ["Flower Pots Special", 470, "1 Box (10 Pcs)", 10, "F", undefined, 94],
    ["Flower Pots Asoka", 600, "1 Box (10 Pcs)", 10, "P", undefined, 120],
    ["Colour Kotti", 1000, "1 Box (10 Pcs)", 10, "N", undefined, 200],
    ["Colour Kotti Deluxe", 1575, "1 Box (10 Pcs)", 10, "PN", undefined, 315],
  ],

  candles: [
    ["Nayagara Falls Handle", 820, "1 Box (5 Pcs)", 5, "F", undefined, 164],
  ],

  rockets: [
    ["Musical Rocket", 1000, "1 Box (10 Pcs)", 10, "B", undefined, 200],
    ["Rocket Bomb", 700, "1 Box (10 Pcs)", 10, "F", undefined, 140],
  ],

  bombs: [
    ["King Bomb", 525, "1 Box (10 Pcs)", 10, "B", undefined, 105],
    ["Classic Bomb", 650, "1 Box (10 Pcs)", 10, "F", undefined, 130],
    ["Jurassic Bomb Or Digital Bomb", 1050, "1 Box (10 Pcs)", 10, "P", undefined, 210],
    ["Paper Bomb 1/4 Kg", 200, "1 Box", 1, "B", undefined, 40],
    ["Paper Bomb 1/2 Kg", 400, "1 Box", 1, "F", undefined, 80],
    ["Paper Bomb 1 Kg", 800, "1 Box", 1, "P", undefined, 160],
  ],

  fountains: [
    ["Tom and Jerry", 400, "1 Box (5 Pcs)", 5, "B", undefined, 80],
    ["Tricolour Fountain", 1400, "1 Box (5 Pcs)", 5, "F", undefined, 280],
    ["Colour Rain", 650, "1 Box (5 Pcs)", 5, "B", undefined, 130],
    ["Fox Star", 675, "1 Box (5 Pcs)", 5, "F", undefined, 135],
    ["Sing Pop", 725, "1 Box (5 Pcs)", 5, "B", undefined, 145],
    ["Helicopter", 475, "1 Box (5 Pcs)", 5, "N", undefined, 95],
    ["Bambaram", 500, "1 Box (10 Pcs)", 10, "B", undefined, 100],
    ["Photo Flash", 260, "1 Box (5 Pcs)", 5, "B", undefined, 52],
    ["Mega Siren", 900, "1 Box (3 Pcs)", 3, "P", undefined, 180],
    ["Mini Siren", 650, "1 Box (3 Pcs)", 3, "B", undefined, 130],
    ["Peacock Feather", 675, "1 Box (2 Pcs)", 2, "F", undefined, 135],
    ["H20 Falls", 750, "1 Box (1 Pc)", 1, "B", undefined, 150],
    ["Colour Smoke", 650, "1 Box (3 Pcs)", 3, "P", undefined, 130],
    ["Faso Stars", 1400, "1 Box (5 Pcs)", 5, "F", undefined, 280],
    ["Water Queen", 650, "1 Box (1 Pc)", 1, "P", undefined, 130],
    ["Tin", 550, "1 Box (1 Pc)", 1, "B", undefined, 110],
    ["Peacock Multicolour", 850, "1 Box (1 Pc)", 1, "P", undefined, 170],
    ["Bada Peacock", 1700, "1 Box (1 Pc)", 1, "PN", undefined, 340],
    ["Money in the Bank (3Pc)", 1150, "1 Box (3 Pcs)", 3, "F", undefined, 230],
    ["4x4 Whistling Wheel", 1100, "1 Box (3 Pcs)", 3, "B", undefined, 220],
    ["Lotus Wheel", 575, "1 Box (3 Pcs)", 3, "F", undefined, 115],
  ],

  "sky-shots": [
    ["Chotta Fancy", 200, "1 Box (1 Pc)", 1, "B", undefined, 40],
    ["2\" Fancy", 550, "1 Box (1 Pc)", 1, "B", undefined, 110],
    ["2\" Fancy (3 Pc)", 1250, "1 Box (3 Pcs)", 3, "F", undefined, 250],
    ["3.5\" Single Smash", 1575, "1 Box (1 Pc)", 1, "F", undefined, 315],
    ["3.5\" Knight Series (2 Pc)", 2625, "1 Box (2 Pcs)", 2, "P", undefined, 525],
    ["3.5\" Double Ball", 2100, "1 Box (1 Pc)", 1, "P", undefined, 420],
    ["4\" Glory Series", 2300, "1 Box (1 Pc)", 1, "P", undefined, 460],
    ["4\" Double Piece", 3950, "1 Box (1 Pc)", 1, "P", undefined, 790],
    ["4\" Nayagara Falls Gold", 1600, "1 Box (1 Pc)", 1, "PN", undefined, 320],
    ["4\" Nayagara Falls Crackling", 1600, "1 Box (1 Pc)", 1, "PN", undefined, 320],
    ["Diwali Fabulous Celebration (16 Shot)", 12500, "1 Box (1 Pc)", 1, "PN", undefined, 2500],
  ],

  "multi-shots": [
    ["15 Shots Colour", 1025, "1 Box (1 Pc)", 1, "B", undefined, 205],
    ["30 Shots Colour", 2050, "1 Box (1 Pc)", 1, "F", undefined, 410],
    ["60 Shots Colour", 4100, "1 Box (1 Pc)", 1, "P", undefined, 820],
    ["120 Shots Colour", 8200, "1 Box (1 Pc)", 1, "PN", undefined, 1640],
    ["240 Shots Colour", 16400, "1 Box (1 Pc)", 1, "PN", undefined, 3280],
  ],

  sparklers: [
    ["7cm Electric Sparklers", 50, "1 Box (10 Pcs)", 10, "B", undefined, 10],
    ["7cm Colour Sparklers", 60, "1 Box (10 Pcs)", 10, "B", undefined, 12],
    ["7cm Green Sparklers", 70, "1 Box (10 Pcs)", 10, "B", undefined, 14],
    ["7cm Red Sparklers", 85, "1 Box (10 Pcs)", 10, "B", undefined, 17],
    ["10cm Electric Sparklers", 100, "1 Box (10 Pcs)", 10, "B", undefined, 20],
    ["10cm Colour Sparklers", 115, "1 Box (10 Pcs)", 10, "B", undefined, 23],
    ["10cm Green Sparklers", 125, "1 Box (10 Pcs)", 10, "F", undefined, 25],
    ["10cm Red Sparklers", 140, "1 Box (10 Pcs)", 10, "F", undefined, 28],
    ["12cm Electric Sparklers", 160, "1 Box (10 Pcs)", 10, "F", undefined, 32],
    ["12cm Colour Sparklers", 190, "1 Box (10 Pcs)", 10, "F", undefined, 38],
    ["12cm Green Sparklers", 200, "1 Box (10 Pcs)", 10, "F", undefined, 40],
    ["12cm Red Sparklers", 210, "1 Box (10 Pcs)", 10, "F", undefined, 42],
    ["15cm Electric Sparklers", 220, "1 Box (10 Pcs)", 10, "P", undefined, 44],
    ["15cm Colour Sparklers", 235, "1 Box (10 Pcs)", 10, "P", undefined, 47],
    ["15cm Green Sparklers", 245, "1 Box (10 Pcs)", 10, "P", undefined, 49],
    ["15cm Red Sparklers", 255, "1 Box (10 Pcs)", 10, "P", undefined, 51],
    ["30cm Electric Sparklers", 250, "1 Box (5 Pcs)", 5, "P", undefined, 50],
    ["30cm Colour Sparklers", 270, "1 Box (5 Pcs)", 5, "P", undefined, 54],
    ["30cm Green Sparklers", 300, "1 Box (5 Pcs)", 5, "P", undefined, 60],
    ["30cm Red Sparklers", 320, "1 Box (5 Pcs)", 5, "P", undefined, 64],
    ["50cm Electric Sparklers", 750, "1 Box (5 Pcs)", 5, "PN", undefined, 150],
    ["50cm Colour Sparklers", 850, "1 Box (5 Pcs)", 5, "PN", undefined, 170],
    ["50cm Red Sparklers", 1350, "1 Box (5 Pcs)", 5, "PN", undefined, 270],
    ["50cm Green Sparklers", 1150, "1 Box (5 Pcs)", 5, "PN", undefined, 230],
  ],

  novelties: [
    ["ROLL CAPS", 250, "1 Box", 10, "B", undefined, 50],
    ["RING CAPS", 250, "1 Box", 10, "B", undefined, 50],
    ["BLACK SERPENTS", 150, "1 Box", 10, "B", undefined, 30],
    ["MEGA 5 in 1 MATCHES", 400, "1 Box (5 Pcs)", 5, "F", undefined, 80],
    ["MAXX MATCHES", 250, "1 Box", 10, "B", undefined, 50],
    ["LAPTOP MEGA 10 in 1 MATCHES", 750, "1 Box (10 Pcs)", 10, "P", undefined, 150],
  ],

  "gift-boxes": [
    ["25 Items (10pc packs)", 1875, "1 Box", 25, "B", undefined, 375],
    ["30 Items (10pc packs)", 2200, "1 Box", 30, "F", undefined, 440],
    ["35 Items (10pc packs)", 2700, "1 Box", 35, "F", undefined, 540],
    ["42 Items (10pc packs)", 4000, "1 Box", 42, "P", undefined, 800],
    ["50 Items (10pc packs)", 5000, "1 Box", 50, "PN", undefined, 1000],
    ["30 Items (5pc packs)", 2000, "1 Box", 30, "FP", undefined, 400],
    ["40 Items (5pc packs)", 3000, "1 Box", 40, "FP", undefined, 600],
    ["50 Items (5pc packs)", 4000, "1 Box", 50, "PN", undefined, 800],
  ],
};

export const SEED_REVIEWS = [
  {
    name: "Karthik Subramanian",
    location: "Chennai, Tamil Nadu",
    rating: 5,
    title: "Factory price, 80% discount quality",
    body: "Ordered a ₹28,000 estimate for our apartment Deepavali. Packing was flawless, 80% off MRP pricing is genuine and sky shots were show-grade.",
  },
  {
    name: "Priya Ramesh",
    location: "Coimbatore, Tamil Nadu",
    rating: 5,
    title: "The kids box & sparklers are brilliant",
    body: "Low sound items actually are low sound. Sparklers and flower pots are genuine Sivakasi quality. Will reorder every year.",
  },
  {
    name: "Mohan Reddy",
    location: "Hyderabad, Telangana",
    rating: 5,
    title: "Best dealer & wholesale pricing",
    body: "I run 3 retail outlets. The 80% discount plus transport coordination saved me nearly 20% versus my previous supplier in Sivakasi.",
  },
  {
    name: "Anitha Vasanth",
    location: "Madurai, Tamil Nadu",
    rating: 5,
    title: "Wedding multi-shot was cinematic",
    body: "We booked the 120 multi color shot ultra for a wedding entry. The team advised on safety distance and the sky show looked stunning.",
  },
  {
    name: "Rajesh Kumar",
    location: "Bengaluru, Karnataka",
    rating: 4,
    title: "Smooth estimate process",
    body: "Submitted estimate at midnight, got a WhatsApp confirmation and a call by 10am. Transparent transport charge — no hidden costs.",
  },
  {
    name: "Fathima Noor",
    location: "Kochi, Kerala",
    rating: 5,
    title: "Genuine Sivakasi stock",
    body: "Everything arrived sealed with batch codes and safety leaflets. This is what factory-direct should feel like.",
  },
];
