export const IMAGE_POOL = [
  "https://images.pexels.com/photos/29440437/pexels-photo-29440437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210634/pexels-photo-31210634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/36745051/pexels-photo-36745051.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/5302663/pexels-photo-5302663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/38128369/pexels-photo-38128369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745603/pexels-photo-12745603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31196818/pexels-photo-31196818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/37125137/pexels-photo-37125137.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/12745602/pexels-photo-12745602.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "https://images.pexels.com/photos/31210664/pexels-photo-31210664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
];

export type SeedCategory = {
  name: string;
  nameTa: string;
  slug: string;
  tagline: string;
  description: string;
  accent: string;
  icon: string;
  imageUrl: string;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: "One Sound / 2 Sound Crackers",
    nameTa: "ஒற்றை & இரட்டை வெடி",
    slug: "single-sound",
    tagline: "Classic Sivakasi Lakshmi, Kuruvi & 2 Sound crackers",
    description: "Traditional single and double report crackers with sharp decibel report.",
    accent: "#FF3131",
    icon: "volume",
    imageUrl: "/categories/single-sound.jpg",
  },
  {
    name: "Bijili Crackers",
    nameTa: "பிஜிலி வெடி",
    slug: "bijili-crackers",
    tagline: "Red and Stripped bijili 100 bags",
    description: "Crisp crackling bijilis packed in 100 piece bags.",
    accent: "#FF3131",
    icon: "zap",
    imageUrl: "/categories/bijili-crackers.jpg",
  },
  {
    name: "Ground Chakkars",
    nameTa: "நிலச்சக்கரம்",
    slug: "ground-chakkar",
    tagline: "Ground Chakkar Big, Special, Deluxe and Spinners",
    description: "High-rpm ground wheels and spinners for kids and families.",
    accent: "#00D26A",
    icon: "disc",
    imageUrl: "/categories/ground-chakkar.jpg",
  },
  {
    name: "Twinkling Stars",
    nameTa: "ட்விங்க்ளிங் ஸ்டார்",
    slug: "twinkling-star",
    tagline: "1½' & 4' Twinkling Star ropes",
    description: "Continuous twinkling stars and star ropes.",
    accent: "#F5D982",
    icon: "star",
    imageUrl: "/categories/twinkling-star.jpg",
  },
  {
    name: "Flower Pots",
    nameTa: "பூச்சட்டி",
    slug: "flower-pots",
    tagline: "Flower Pots Big, Special, Asoka & Colour Kotti",
    description: "Classic high-rise golden and silver fountains with low smoke composition.",
    accent: "#D4AF37",
    icon: "sparkles",
    imageUrl: "/categories/flower-pots.jpg",
  },
  {
    name: "Pencils",
    nameTa: "பென்சில்ஸ்",
    slug: "candles",
    tagline: "Nayagara Falls Handle pencils",
    description: "Multi-color fountain handle pencils.",
    accent: "#00D26A",
    icon: "flame",
    imageUrl: "/categories/candles.jpg",
  },
  {
    name: "Rockets",
    nameTa: "ராக்கெட்",
    slug: "rockets",
    tagline: "Musical Rocket and Rocket Bomb",
    description: "High-flying rockets with whistling sound and bright canopy bursts.",
    accent: "#FF8C00",
    icon: "rocket",
    imageUrl: "/categories/rockets.jpg",
  },
  {
    name: "Bombs",
    nameTa: "பாம் வகைகள்",
    slug: "bombs",
    tagline: "King Bomb, Classic Bomb, Jurassic & Paper Bombs",
    description: "High-decibel sound bombs with heavy casing and water-resistant fuse.",
    accent: "#FF3131",
    icon: "bomb",
    imageUrl: "/categories/bombs.jpg",
  },
  {
    name: "Fountains",
    nameTa: "ஃபவுண்டன் வகைகள்",
    slug: "fountains",
    tagline: "Tom & Jerry, Peacock, Water Queen & Novelty Fountains",
    description: "Vibrant shower cones, multi-step fountains and tri-color pyro fountain displays.",
    accent: "#FF8C00",
    icon: "flame",
    imageUrl: "/categories/fountains.jpg",
  },
  {
    name: "Aerial Shots",
    nameTa: "வான வெடி",
    slug: "sky-shots",
    tagline: "Chotta Fancy, 2″ Fancy, 3.5″ Smash & Nayagara Falls",
    description: "Single sky displays and aerial shells.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Multi Shots",
    nameTa: "மல்டி ஷாட்ஸ்",
    slug: "multi-shots",
    tagline: "15 to 240 Shots Colour sky repeaters",
    description: "Aerial multi-color sky repeaters and celebration set outs.",
    accent: "#0057FF",
    icon: "rocket",
    imageUrl: "/categories/sky-shots.jpg",
  },
  {
    name: "Sparklers",
    nameTa: "மத்தாப்பு",
    slug: "sparklers",
    tagline: "7cm to 50cm Electric, Colour, Green & Red sparklers",
    description: "Child-safe sparklers with bright light and low smoke emission.",
    accent: "#F5D982",
    icon: "wand",
    imageUrl: "/categories/sparklers.jpg",
  },
  {
    name: "Colour Matches & Novelties",
    nameTa: "தீப்பெட்டி & ஃபேன்சி",
    slug: "novelties",
    tagline: "Roll Caps, Ring Caps, Black Serpents & Mega Matches",
    description: "Match boxes, caps, serpents and novelties.",
    accent: "#FF8C00",
    icon: "gift",
    imageUrl: "/categories/novelties.jpg",
  },
  {
    name: "Gift Boxes",
    nameTa: "கிஃப்ட் பாக்ஸ்",
    slug: "gift-boxes",
    tagline: "21 to 51 Items & Family Combo / VIP Packs",
    description: "Curated festival packages containing a balanced mix across all categories.",
    accent: "#D4AF37",
    icon: "package",
    imageUrl: "/categories/gift-boxes.jpg",
  },
];

export const SEED_PRODUCTS: Record<string, [string, number, string, number, string?, string?][]> = {
  "single-sound": [
    ["2 3/4\" Kuruvi", 100, "1 Box", 5, "B"],
    ["3 1/2\" Laxmi", 150, "1 Box", 5, "B"],
    ["4\" Laxmi", 200, "1 Box", 5, "F"],
    ["4\" Deluxe Laxmi", 250, "1 Box", 5, "N"],
    ["4\" Gold Laxmi", 300, "1 Box", 5, "P"],
    ["5\" Laxmi", 350, "1 Box", 5, "PN"],
    ["2 Sound", 300, "1 Box", 5, "B"],
  ],

  "bijili-crackers": [
    ["Red Bijili 100", 250, "1 Bag (100 Pcs)", 100, "B"],
    ["Stripped Bijili 100", 300, "1 Bag (100 Pcs)", 100, "F"],
  ],

  "ground-chakkar": [
    ["Ground Chakkar Big 10Pcs", 350, "1 Box (10 Pcs)", 10, "B"],
    ["Ground Chakkar Special", 450, "1 Box (10 Pcs)", 10, "F"],
    ["Ground Chakkar Deluxe", 550, "1 Box (10 Pcs)", 10, "P"],
    ["Spinner Deluxe", 600, "1 Box (5 Pcs)", 5, "N"],
  ],

  "twinkling-star": [
    ["1 1/2' Twinkling Stars", 150, "1 Box (10 Pcs)", 10, "B"],
    ["4' Twinkling Stars", 350, "1 Box (10 Pcs)", 10, "F"],
  ],

  "flower-pots": [
    ["Flower Pots Big", 400, "1 Box (10 Pcs)", 10, "B"],
    ["Flower Pots Special", 550, "1 Box (10 Pcs)", 10, "F"],
    ["Flower Pots Asoka", 700, "1 Box (10 Pcs)", 10, "P"],
    ["Colour Kotti", 850, "1 Box (10 Pcs)", 10, "N"],
    ["Colour Kotti Deluxe", 1000, "1 Box (10 Pcs)", 10, "PN"],
  ],

  candles: [
    ["Nayagara Falls Handle", 450, "1 Box (5 Pcs)", 5, "F"],
  ],

  rockets: [
    ["Musical Rocket", 600, "1 Box (10 Pcs)", 10, "B"],
    ["Rocket Bomb", 700, "1 Box (10 Pcs)", 10, "F"],
  ],

  bombs: [
    ["King Bomb", 500, "1 Box (10 Pcs)", 10, "B"],
    ["Classic Bomb", 600, "1 Box (10 Pcs)", 10, "F"],
    ["Jurassic Bomb Or Digital Bomb", 800, "1 Box (10 Pcs)", 10, "P"],
    ["Paper Bomb 1/4 Kg", 450, "1 Box", 1, "B"],
    ["Paper Bomb 1/2 Kg", 750, "1 Box", 1, "F"],
    ["Paper Bomb 1 Kg", 1200, "1 Box", 1, "P"],
  ],

  fountains: [
    ["Tom and Jerry", 600, "1 Box (5 Pcs)", 5, "B"],
    ["Tricolour Fountain", 800, "1 Box (5 Pcs)", 5, "F"],
    ["Colour Rain", 650, "1 Box (5 Pcs)", 5, "B"],
    ["Fox Star", 700, "1 Box (5 Pcs)", 5, "F"],
    ["Sing Pop", 500, "1 Box (5 Pcs)", 5, "B"],
    ["Drone", 750, "1 Box (5 Pcs)", 5, "F"],
    ["Helicopter", 800, "1 Box (5 Pcs)", 5, "N"],
    ["Bambaram", 450, "1 Box (10 Pcs)", 10, "B"],
    ["Photo Flash", 400, "1 Box (5 Pcs)", 5, "B"],
    ["Insta Selfie", 650, "1 Box (5 Pcs)", 5, "F"],
    ["Mega Siren", 900, "1 Box (3 Pcs)", 3, "P"],
    ["Mini Siren", 600, "1 Box (3 Pcs)", 3, "B"],
    ["Peacock Feather", 850, "1 Box (2 Pcs)", 2, "F"],
    ["H20 Falls", 750, "1 Box (1 Pc)", 1, "B"],
    ["Colour Smoke", 650, "1 Box (3 Pcs)", 3, "P"],
    ["Free Fire Gun", 950, "1 Box (1 Pc)", 1, "N"],
    ["Faso Stars", 800, "1 Box (5 Pcs)", 5, "F"],
    ["Pocket / Lima / Jazz Stars", 850, "1 Box (5 Pcs)", 5, "B"],
    ["Little Simba", 700, "1 Box (3 Pcs)", 3, "B"],
    ["Magical Unicorn", 900, "1 Box (2 Pcs)", 2, "F"],
    ["Pink Nova", 850, "1 Box (2 Pcs)", 2, "N"],
    ["Violet Nebula", 850, "1 Box (2 Pcs)", 2, "N"],
    ["Water Queen", 950, "1 Box (1 Pc)", 1, "P"],
    ["Tin", 600, "1 Box (1 Pc)", 1, "B"],
    ["Peacock Multicolour", 1100, "1 Box (1 Pc)", 1, "P"],
    ["Bada Peacock", 1800, "1 Box (1 Pc)", 1, "PN"],
    ["Money in the Bank (3Pc)", 1200, "1 Box (3 Pcs)", 3, "F"],
    ["4x4 Whistling Wheel", 850, "1 Box (3 Pcs)", 3, "B"],
    ["Lotus Wheel", 750, "1 Box (3 Pcs)", 3, "F"],
  ],

  "sky-shots": [
    ["Chotta Fancy", 300, "1 Box (1 Pc)", 1, "B"],
    ["2\" Fancy", 600, "1 Box (1 Pc)", 1, "B"],
    ["2\" Fancy (3 Pc)", 1500, "1 Box (3 Pcs)", 3, "F"],
    ["3.5\" Single Smash", 1600, "1 Box (1 Pc)", 1, "F"],
    ["3.5\" Knight Series (2 Pc)", 2800, "1 Box (2 Pcs)", 2, "P"],
    ["3.5\" Double Ball", 1800, "1 Box (1 Pc)", 1, "P"],
    ["4\" Glory Series", 2200, "1 Box (1 Pc)", 1, "P"],
    ["4\" Double Piece", 2500, "1 Box (1 Pc)", 1, "P"],
    ["4\" Nayagara Falls Gold", 2400, "1 Box (1 Pc)", 1, "PN"],
    ["4\" Nayagara Falls Crackling", 2600, "1 Box (1 Pc)", 1, "PN"],
    ["Diwali Fabulous Celebration (16 Shot)", 3200, "1 Box (1 Pc)", 1, "PN"],
  ],

  "multi-shots": [
    ["15 Shots Colour", 1200, "1 Box (1 Pc)", 1, "B"],
    ["30 Shots Colour", 2200, "1 Box (1 Pc)", 1, "F"],
    ["60 Shots Colour", 4200, "1 Box (1 Pc)", 1, "P"],
    ["120 Shots Colour", 8500, "1 Box (1 Pc)", 1, "PN"],
    ["240 Shots Colour", 16500, "1 Box (1 Pc)", 1, "PN"],
  ],

  sparklers: [
    ["7cm Electric Sparklers", 80, "1 Box (10 Pcs)", 10, "B"],
    ["7cm Colour Sparklers", 90, "1 Box (10 Pcs)", 10, "B"],
    ["7cm Green Sparklers", 100, "1 Box (10 Pcs)", 10, "B"],
    ["7cm Red Sparklers", 110, "1 Box (10 Pcs)", 10, "B"],
    ["10cm Electric Sparklers", 120, "1 Box (10 Pcs)", 10, "B"],
    ["10cm Colour Sparklers", 130, "1 Box (10 Pcs)", 10, "B"],
    ["10cm Green Sparklers", 140, "1 Box (10 Pcs)", 10, "F"],
    ["10cm Red Sparklers", 150, "1 Box (10 Pcs)", 10, "F"],
    ["12cm Electric Sparklers", 160, "1 Box (10 Pcs)", 10, "F"],
    ["12cm Colour Sparklers", 170, "1 Box (10 Pcs)", 10, "F"],
    ["12cm Green Sparklers", 180, "1 Box (10 Pcs)", 10, "F"],
    ["12cm Red Sparklers", 190, "1 Box (10 Pcs)", 10, "F"],
    ["15cm Electric Sparklers", 220, "1 Box (10 Pcs)", 10, "P"],
    ["15cm Colour Sparklers", 240, "1 Box (10 Pcs)", 10, "P"],
    ["15cm Green Sparklers", 260, "1 Box (10 Pcs)", 10, "P"],
    ["15cm Red Sparklers", 280, "1 Box (10 Pcs)", 10, "P"],
    ["30cm Electric Sparklers", 320, "1 Box (5 Pcs)", 5, "P"],
    ["30cm Colour Sparklers", 350, "1 Box (5 Pcs)", 5, "P"],
    ["30cm Green Sparklers", 380, "1 Box (5 Pcs)", 5, "P"],
    ["30cm Red Sparklers", 400, "1 Box (5 Pcs)", 5, "P"],
    ["50cm Electric Sparklers", 850, "1 Box (5 Pcs)", 5, "PN"],
    ["50cm Colour Sparklers", 900, "1 Box (5 Pcs)", 5, "PN"],
    ["50cm Red Sparklers", 950, "1 Box (5 Pcs)", 5, "PN"],
    ["50cm Green Sparklers", 1000, "1 Box (5 Pcs)", 5, "PN"],
  ],

  novelties: [
    ["ROLL CAPS", 200, "1 Box", 10, "B"],
    ["RING CAPS", 250, "1 Box", 10, "B"],
    ["BLACK SERPENTS", 150, "1 Box", 10, "B"],
    ["MEGA 5 in 1 MATCHES", 450, "1 Box (5 Pcs)", 5, "F"],
    ["MAXX MATCHES", 300, "1 Box", 10, "B"],
    ["LAPTOP MEGA 10 in 1 MATCHES", 850, "1 Box (10 Pcs)", 10, "P"],
  ],

  "gift-boxes": [
    ["21 Items", 1500, "1 Box", 21, "B"],
    ["31 Items", 2500, "1 Box", 31, "F"],
    ["41 Items", 3800, "1 Box", 41, "F"],
    ["51 Items", 5200, "1 Box", 51, "P"],
    ["Family Combo Pack", 4500, "1 Box", 40, "FP"],
    ["VIP Family Pack", 8500, "1 Box", 65, "PN"],
  ],
};

export const SEED_REVIEWS = [
  {
    name: "Karthik Subramanian",
    location: "Chennai, Tamil Nadu",
    rating: 5,
    title: "Factory price, 80% discount quality",
    body: "Ordered a ₹28,000 estimate for our apartment Deepavali. Packing was flawless, 80% off MRP pricing is genuine and sky shots were show-grade.",
  },
  {
    name: "Priya Ramesh",
    location: "Coimbatore, Tamil Nadu",
    rating: 5,
    title: "The kids box & sparklers are brilliant",
    body: "Low sound items actually are low sound. Sparklers and flower pots are genuine Sivakasi quality. Will reorder every year.",
  },
  {
    name: "Mohan Reddy",
    location: "Hyderabad, Telangana",
    rating: 5,
    title: "Best dealer & wholesale pricing",
    body: "I run 3 retail outlets. The 80% discount plus transport coordination saved me nearly 20% versus my previous supplier in Sivakasi.",
  },
  {
    name: "Anitha Vasanth",
    location: "Madurai, Tamil Nadu",
    rating: 5,
    title: "Wedding multi-shot was cinematic",
    body: "We booked the 120 multi color shot ultra for a wedding entry. The team advised on safety distance and the sky show looked stunning.",
  },
  {
    name: "Rajesh Kumar",
    location: "Bengaluru, Karnataka",
    rating: 4,
    title: "Smooth estimate process",
    body: "Submitted estimate at midnight, got a WhatsApp confirmation and a call by 10am. Transparent transport charge — no hidden costs.",
  },
  {
    name: "Fathima Noor",
    location: "Kochi, Kerala",
    rating: 5,
    title: "Genuine Sivakasi stock",
    body: "Everything arrived sealed with batch codes and safety leaflets. This is what factory-direct should feel like.",
  },
];
